### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sorah** [kenfdev/remo-exporter#14]
## Expected Behavior

license is declared for this repository

## Current Behavior

No LICENSE file and license terms found in the repository

## Possible Solution

Declare license (I expect OSS license but you may use your own)

## Detailed Description

I just looked into this repository and tried to deploy, but I'm hesitating to use this because there's no license declared. I need to know the license used for the code in this repository. 

(of course you may retain your code "all rights reserved")

**Comment by kenfdev** [comment]
Thanks for the heads up @sorah !

I've added the MIT License file to the repo. Hope this exporter comes in handy.

**Comment by sorah** [comment]
thanks!

btw didn't notice there was an contributor; @8398a7 FYI the code in this repository is now licensed under MIT where includes your contribution.

**Comment by kenfdev** [comment]
Many thanks, @sorah and apologies for the LICENSE ignorance. Please let me know any issues you find on the run 🙏
