### ISSUE TITLE
Change to use Go modules instead of Dep for package management

### ISSUE THREAD

**Issue by bean1310** [kenfdev/remo-exporter#23]
## Expected Behavior
Use Go Modules for package management.

## Current Behavior
Dep is used for package management.

## Possible Solution
Delete Gopkg.toml & Gopkg.lock files and add go.mod & go.sum files.

## Context (Environment)
I'm developing a new feature of this Prometheus exporter.
This development is difficult because Dep is a deprecated package manager now.
Therefore, I need to change to a standard package manager.

## Possible Implementation
I am ready to solve this issue.
May I create PR?

**Comment by kenfdev** [comment]
@bean1310 
Thanks for opening an issue!  I've been away from Go development for a while so am happy to accept any contribution to make this product better :)
As long as the tests pass, I think this is going to be great!

**Comment by kenfdev** [comment]
@bean1310 
I've merged #24 and updated CircleCI to release the master image 👍 
Could you please check if the image works as expected?

https://hub.docker.com/layers/kenfdev/remo-exporter/master/images/sha256-df6f38325c6eecb93d574b40ff33f9901e53de819552dffe56cced936cff9ef0?context=repo

If it does, I'll create a release tag for a new release!

**Comment by bean1310** [comment]
@kenfdev 
Thank you to merge #24.

But, I found a new problem during checking images.
Therefore, I fix it in #26.
Please check it.

**Comment by kenfdev** [comment]
@bean1310 
Awesome :) Thanks a lot!
I've merged it and here's the new image.

https://hub.docker.com/layers/kenfdev/remo-exporter/master/images/sha256-88e18c21691c54dad4cf7cdcb5df284847f0f1739266faa72a8731f943e1389e?context=explore

Could you give it another try?
If it looks good, I'll create tag 👍

**Comment by bean1310** [comment]
LGTM !!
Thank you for merging!

**Comment by kenfdev** [comment]
@bean1310 
Thank you for your contribution! I've released v0.8.0

https://hub.docker.com/layers/kenfdev/remo-exporter/0.8.0/images/sha256-fa187a6f59394af0e517336bd831b78bf9593147671e46e94cc5ded9851a380d?context=explore

Please take a look!
